Repository arkhn/fhir-river, pull requests merged in 2021-11, with the labels that each got.

#703 Fix exploration cells with `NULL` value
  app/src/features/Preview/Preview.tsx
Labels: bug, Pyrog Rebirth

#688 Add fixed value as static input
  app/src/features/FhirResourceTree/useFhirResourceTreeData.ts
  app/src/features/FhirResourceTree/useInitNodeFixedValue.ts
  app/src/features/Inputs/StaticInput.tsx
Labels: Pyrog Rebirth, fhir-compliance

#706 Fix requests performance optimisations
  app/src/common/hooks/useIsNodePending.tsx
  app/src/services/api/generated/api.generated.ts
  django/pyrog/api/filters.py
  river-schema.yml
  tests/pyrog/api/test_input_group.py
  tests/pyrog/api/test_sql_input.py
  tests/pyrog/api/test_static_input.py
Labels: bug, medium priority, Pyrog Rebirth

#704 Display errors 404 and better handle of snackbars
  app/src/app/App.tsx
  app/src/app/middlewares.ts
  app/src/app/store.ts
  app/src/features/Batches/BatchCancel.tsx
  app/src/features/Batches/BatchResourceDialog.tsx
  app/src/features/Columns/useColumn.ts
  app/src/features/Conditions/useCondition.ts
  app/src/features/FhirResourceTree/FhirResourceTree.tsx
  app/src/features/InputGroups/InputGroup.tsx
  app/src/features/Inputs/SqlInput.tsx
  app/src/features/Inputs/StaticInput.tsx
  app/src/features/Inputs/useSqlInput.ts
  app/src/features/Joins/useJoin.ts
  app/src/features/Mappings/Create/CreateMapping.tsx
  app/src/features/Notifications/notificationSlice.ts
  app/src/features/Notifications/useNotifications.ts
  app/src/features/Scripts/MergingScript.tsx
  app/src/features/Sources/UploadSourceButton.tsx
  app/src/features/ValueSets/ValueSetSelect.tsx
Labels: bug, high priority, Pyrog Rebirth

#717 [Fix] Create attribute for nodes of type `Reference`
  app/src/features/FhirResourceTree/useFhirResourceTreeData.ts
Labels: type/enhancement, proj/new-pyrog

#721 [Fix] Node pending state when choice is attribute ancestor
  app/src/common/hooks/useIsNodePending.tsx
Labels: type/bug, proj/new-pyrog
