Repository arkhn/fhir-river, pull requests merged in 2021-08, with the labels that each got.

#543 Change UI for ETL view
  app/src/app/routes/Sources/Batches/Batches.tsx
  app/src/app/routes/Sources/Mappings/MappingHeader.tsx
  app/src/app/routes/Sources/SourceMappings.tsx
  app/src/features/Batches/BatchCancel.tsx
  app/src/features/Batches/BatchCreate.tsx
  app/src/features/Batches/BatchErrors.tsx
  app/src/features/Batches/BatchList.tsx
  app/src/features/NavigationBreadcrumbs/NavigationBreadcrumbs.tsx
Labels: enhancement, Pyrog Rebirth

#511 feat(app): pass a mapping to batch and preview endpoints
  app/package.json
  app/src/app/routes/Sources/__tests__/Sources.test.tsx
  app/src/common/helpers/__tests__/conceptMaps.test.ts
  app/src/common/helpers/conceptMaps.ts
  app/src/common/hooks/useMergeConceptMapsToMappings.ts
  app/src/common/test/data/conceptMaps.json
  app/src/common/test/data/mappings.json
  app/src/common/test/data/mappingsWithConceptMaps.json
  app/src/features/Batches/BatchCreate.tsx
  app/src/features/FhirAttributePanel/SqlInput.tsx
  app/src/features/FhirAttributePanel/StaticInput.tsx
  app/src/features/Preview/Preview.tsx
  app/src/features/Sources/UploadSourceButton.tsx
  app/src/services/api/endpoints.ts
  app/src/services/api/generated/api.generated.ts
  app/yarn.lock
  django/pyrog/api/serializers/import_export.py
  django/river/api/serializers/mapping.py
  river-schema.yml
Labels: Pyrog Rebirth

#547 auto-create condition when adding a new input group
  app/src/features/FhirAttributePanel/AttributeInputGroup.tsx
  app/src/features/FhirAttributePanel/FhirAttributePanel.tsx
Labels: Pyrog Rebirth

#539 Pre-fill table with mapping table when adding a new dynamic input
  app/src/features/FhirAttributePanel/Condition.tsx
  app/src/features/FhirAttributePanel/FhirAttributePanel.tsx
  app/src/features/FhirAttributePanel/SqlInput.tsx
  app/src/features/Joins/FilterJoinList.tsx
Labels: enhancement, Pyrog Rebirth

#585 White Import Source icon
  app/src/features/Sources/UploadSourceButton.tsx
Labels: Pyrog Rebirth, ui

#586 [FHIR Preview] Show an Alert component instead of a snackbar
  app/src/features/Preview/Preview.tsx
Labels: Pyrog Rebirth, ui

#589 Required dot displays only on required attributes (not recursive)
  app/src/features/FhirResourceTree/TreeNodeBadge.tsx
  app/src/features/FhirResourceTree/resourceTreeUtils.ts
Labels: bug, Pyrog Rebirth
