Repository arkhn/fhir-river, pull requests merged in 2021-10, with the labels that each got.

#625 [ETL dashboard] - new UI for batch list
  app/package.json
  app/public/index.html
  app/src/constants.ts
  app/src/features/Batches/BatchList.tsx
  app/src/features/Batches/BatchListItem.tsx
  app/src/features/Batches/BatchResourceDialog.tsx
  app/src/locales/en.json
  app/yarn.lock
Labels: ui

#636 Split add input button into 2 buttons
  app/src/common/components/Button.tsx
  app/src/features/FhirAttributePanel/InputGroup.tsx
  app/src/locales/en.json
Labels: Pyrog Rebirth

#649 Fix `Generate URI` button disabled
  app/src/features/Inputs/StaticInput.tsx
Labels: bug, Pyrog Rebirth

#641 Add SearchBar to Merging Script
  app/src/features/Scripts/MergingScript.tsx
Labels: bug, medium priority, Pyrog Rebirth

#615 [ETL dashboard] - better UX for launching river batches
  app/package.json
  app/public/index.html
  app/src/app/routes/Router.tsx
  app/src/app/routes/Sources/Batches/BatchCreate.tsx
  app/src/app/routes/Sources/Batches/Batches.tsx
  app/src/app/routes/Sources/Sources.tsx
  app/src/common/components/Button.tsx
  app/src/constants.ts
  app/src/features/Batches/BatchCreate.tsx
  app/src/features/Batches/BatchErrors.tsx
  app/src/features/Batches/BatchList.tsx
  app/src/features/Batches/BatchListItem.tsx
  app/src/features/Batches/BatchResourceDialog.tsx
  app/src/features/Batches/BatchResourceListItem.tsx
  app/src/features/FhirAttributePanel/FhirAttributePanel.tsx
  app/src/features/FhirAttributePanel/InputGroup.tsx
  app/src/features/Inputs/SqlInput.tsx
  app/src/features/Joins/FilterJoinList.tsx
  app/src/features/Joins/SqlInputJoinList.tsx
  app/src/features/Mappings/Create/TableStep.tsx
  app/src/features/Navbar/MappingSelectButton.tsx
  app/src/features/Preview/Preview.tsx
  app/src/features/Scripts/CleaningScriptButton.tsx
  app/src/features/Sources/CredentialDialog.tsx
  app/src/features/Sources/CredentialForm.tsx
  app/src/features/Sources/SourceDrawer.tsx
  app/src/features/Sources/SourceForm.tsx
  app/src/features/Sources/UploadSourceButton.tsx
  app/src/locales/en.json
  app/src/services/api/generated/api.generated.ts
  app/yarn.lock
Labels: Pyrog Rebirth, ui
