Repository arkhn/fhir-river, pull requests merged in 2021-09, with the labels that each got.

#598 Fix refetch serialized mappings for exports
  app/src/app/routes/Sources/SourceExportButton.tsx
Labels: bug, Pyrog Rebirth

#603 Create static input for node of type "URI" & name "type"
  app/src/features/FhirResourceTree/FhirResourceTree.tsx
Labels: enhancement, Pyrog Rebirth

#617 Better handle of alert component
  app/package.json
  app/src/app/App.tsx
  app/src/common/components/Alert.tsx
  app/src/common/test/test-utils.tsx
  app/src/features/Batches/BatchCancel.tsx
  app/src/features/Batches/BatchCreate.tsx
  app/src/features/FhirResourceTree/FhirResourceTree.tsx
  app/src/features/Inputs/SqlInput.tsx
  app/src/features/Mappings/Create/CreateMapping.tsx
  app/src/features/Mappings/Create/UploadProfileListItem.tsx
  app/src/features/Mappings/Delete/MappingDeleteDialog.tsx
  app/src/features/Mappings/Edit/EditMapping.tsx
  app/src/features/Mappings/Edit/MappingNameDialog.tsx
  app/src/features/Preview/Preview.tsx
  app/src/features/Scripts/MergingScript.tsx
  app/src/features/Sources/CredentialForm.tsx
  app/src/features/Sources/CredentialOwnersSelect.tsx
  app/src/features/Sources/UploadSourceButton.tsx
  app/yarn.lock
Labels: Pyrog Rebirth

#627 [FHIR Preview] - Show all errors on fhir preview
  app/src/features/Preview/Preview.tsx
Labels: bug, Pyrog Rebirth
